# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'wait for players'), (1, 'no card shown'), (2, 'one_card_shown'), (3, 'game ended')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretid', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='memory.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memory.Player'),
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='memory.Game'),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memory.Image'),
        ),
    ]
