# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_auto_20160204_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='offset_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='offset_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
