# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_card_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='position',
        ),
        migrations.RemoveField(
            model_name='card',
            name='shown',
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(0, 'backside'), (1, 'frontside'), (2, 'removed')], default=0),
        ),
    ]
